@startuml Sequence_Matchmaking_Game
skinparam dpi 300
skinparam shadowing false
title Sequence diagram --- Matchmaking and live move

actor PlayerA as A
actor PlayerB as B
participant "Lobby / game\n(Angular A)" as UI_A
participant "Lobby / game\n(Angular B)" as UI_B
participant "Server" as S
database "SQLite" as DB

A -> UI_A : Join queue
UI_A -> S : Join matchmaking
S -> DB : Save queue entry
B -> UI_B : Join queue
UI_B -> S : Join matchmaking
S -> DB : Create Game
S --> UI_A : Match found
S --> UI_B : Match found
A -> UI_A : Plays a move
UI_A -> S : Play move
S -> DB : Save Move
S --> UI_A : New position
S --> UI_B : New position
@enduml
